spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products-api
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
